ClusterName=local
SlurmctldHost=localhost
SlurmUser=slurm
SlurmdUser=root
AuthType=auth/munge
MailProg=/bin/true
StateSaveLocation=/var/spool/slurmctld
SlurmdSpoolDir=/var/spool/slurmd
SlurmctldPidFile=/run/slurmctld.pid
SlurmdPidFile=/run/slurmd.pid
SwitchType=switch/none
MpiDefault=none
ProctrackType=proctrack/pgid
TaskPlugin=task/affinity
JobAcctGatherType=jobacct_gather/none
ReturnToService=1
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core_Memory
AccountingStorageType=accounting_storage/none
JobCompType=jobcomp/none

SlurmctldPort=6817
SlurmdPort=6818

NodeName=slurm CPUs=8 Sockets=1 CoresPerSocket=4 ThreadsPerCore=2 RealMemory=8192 State=UNKNOWN
PartitionName=debug Nodes=slurm Default=YES MaxTime=INFINITE State=UP
